package org.broadleafcommerce.payment.service.gateway;

import com.broadleafcommerce.paymentgateway.service.transaction.PaymentGatewayTransactionService;

public interface PayPalCheckoutTransactionService extends PaymentGatewayTransactionService {}
